"""Generate the run-dependent tables in design.md from the database.

    cd backend && python -m scripts.design_tables            # latest run
    cd backend && python -m scripts.design_tables <run_key>  # a specific run

design.md has to quote a real funnel, the real venues that were selected, and the
real rejections. Typing those by hand invites them to drift from what the
pipeline actually did. This reads the run back from the database and prints
markdown to paste into the marked sections. Re-run it after any pipeline run.
"""

from __future__ import annotations

import sys

from app.schemas import ResultsPayload
from app.services import repository


def _funnel_table(p: ResultsPayload) -> str:
    f = p.funnel
    rows = [
        ("Pulled from Google Places", f.discovered, "Text Search across 5 areas x 3 categories"),
        ("Survived chain / indoor filters", f.after_chain_filter, "Name blocklist + container terms"),
        ("Survived status / review filters", f.after_status_filter, "OPERATIONAL, >= 5 reviews"),
        ("Entered the paid stages", f.entered_pipeline, "Capped by MAX_VENUES"),
        ("Frontage photographed", f.capture_ok, "Street View, or Places Photos fallback"),
        ("Passed vision assessment", f.assess_ok, "Entrance visible, framing usable, bare enough"),
        ("Scale measured", f.measure_ok, "Door found and within sanity bounds"),
        ("Composite generated", f.composite_ok, "Nano Banana returned an image"),
        ("**Accepted**", f.accepted, "**Passed verification — safe to send**"),
    ]
    out = ["| Stage | Remaining | Gate |", "|---|---:|---|"]
    out += [f"| {label} | {n} | {note} |" for label, n, note in rows]
    return "\n".join(out)


def _venues_table(p: ResultsPayload) -> str:
    if not p.venues:
        return "_No venues accepted in this run._"
    out = [
        "| Venue | Address | Postcode | Bareness | Source | Planter | Attempts |",
        "|---|---|---|---:|---|---|---:|",
    ]
    for v in p.venues:
        src = "Street View" if v.image_source == "streetview" else "Places photo"
        if v.heading_used is not None:
            src += f" @ {v.heading_used:.0f}°"
        out.append(
            f"| {v.name} | {v.address} | {v.postcode or '—'} | "
            f"{v.assessment.frontage_bare_score}/10 | {src} | "
            f"{v.product_slug.replace('_', ' ')} | {v.attempts} |"
        )
    return "\n".join(out)


def _rejections_table(p: ResultsPayload) -> str:
    if not p.rejected:
        return "_Nothing was rejected in this run._"
    out = ["| Venue | Stage | Reason |", "|---|---|---|"]
    for r in p.rejected:
        reason = "; ".join(r.reasons).replace("|", "\\|")
        out.append(f"| {r.venue_name} | {r.stage} | {reason} |")
    return "\n".join(out)


def _rejection_summary(p: ResultsPayload) -> str:
    by_stage: dict[str, int] = {}
    for r in p.rejected:
        by_stage[r.stage] = by_stage.get(r.stage, 0) + 1
    if not by_stage:
        return "_No rejections._"
    out = ["| Stage | Rejected |", "|---|---:|"]
    out += [f"| {s} | {n} |" for s, n in sorted(by_stage.items(), key=lambda kv: -kv[1])]
    return "\n".join(out)


def main() -> int:
    # Read the latest run from the database (optionally a specific one via argv).
    run_key = sys.argv[1] if len(sys.argv) > 1 else None
    p = repository.get_run(run_key)
    if p is None:
        print("No runs found in the database. Run the pipeline first, or check SUPABASE_* config.")
        return 1

    print(f"<!-- Generated by scripts/design_tables.py from run {p.run_id} -->")
    print(f"<!-- Image model: {p.image_model or 'n/a'}{' | DRY RUN' if p.dry_run else ''} -->\n")
    print("### The funnel\n")
    print(_funnel_table(p))
    print("\n### The chosen venues\n")
    print(_venues_table(p))
    print("\n### Rejections by stage\n")
    print(_rejection_summary(p))
    print("\n### Every rejection, with its reason\n")
    print(_rejections_table(p))
    return 0


if __name__ == "__main__":
    sys.exit(main())
